app/models.py
from flask_mongoengine import MongoEngine
from datetime import datetime

db = MongoEngine()


class User(db.Document):
    name = db.StringField(required=True, max_length=64)
    password = db.StringField(max_length=256)
    email = db.StringField(max_length=64)
    description = db.StringField(max_length=1024)

    # Flask-Login integration
    def is_authenticated(self):
        return True

    def is_active(self):
        return True

    def is_anonymous(self):
        return False

    # TypeError: ObjectId('552f41e56a85f00dd043406b') is not JSON serializable
    def get_id(self):
        return str(self.id)

    def __unicode__(self):
        return self.name

post_status = ((0, 'draft'), (1, 'published'))


class Post(db.Document):
    title = db.StringField(required=True, max_length=64)
    content = db.StringField(required=True)
    author = db.ReferenceField(User)
    tags = db.ListField(db.StringField(max_length=32))
    status = db.IntField(required=True, choices=post_status)
    create_time = db.DateTimeField(default=datetime.now)
    modify_time = db.DateTimeField(default=datetime.now)

    def __unicode__(self):
        return self.title

    meta = {
        'ordering': ['-create_time']
    }

app/admin/forms.py
from wtforms import StringField,PasswordField
from wtforms import form
from wtforms import validators
from wtforms.validators import DataRequired
from app.models import User
from werkzeug.security import check_password_hash


class LoginForm(form.Form):
    name = StringField('name', validators=[DataRequired()])
    password = PasswordField('password', validators=[DataRequired()])

    def get_user(self):
        user = User.query.filter_by(name=self.name.data).first()
        return user

    def validate_name(self, field):
        user = self.get_user()
        if user:
            if not check_password_hash(user.password, self.password.data):
                raise validators.ValidationError('password error')

        else:
            raise validators.ValidationError('user error')

app/__init__.py
from flask import Flask
from models import db
from views import bp
from app.admin import create_admin
from flask_login import LoginManager
from app.filters import babel, my_format_datetime, format_meta_keywords


def create_app():

    app = Flask(__name__)
    app.config.from_object('config')

    register_babel(app)
    register_jinjia_filters(app)
    init_login(app)
    register_blueprints(app)
    register_database(app)
    create_admin(app)

    return app


def register_blueprints(app):
    app.register_blueprint(bp)


def register_database(app):
    db.init_app(app)


def init_login(app):
    login_manager = LoginManager()
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(user_id):
        from app.models import User
        return User.objects(id=user_id).first()


def register_babel(app):
    babel.init_app(app)


def register_jinjia_filters(app):
    app.jinja_env.filters['my_format_datetime'] = my_format_datetime
    app.jinja_env.filters['format_meta_keywords'] = format_meta_keywords

app/admin/__init__.py
from flask_admin import Admin
from views import UserView, PostView, MyIndexView
from app.models import User, Post


def create_admin(app=None):
    admin = Admin(app, name="CleanBlogAdmin", index_view=MyIndexView(), base_template='admin/my_master.html')
    admin.add_view(UserView(User))
    admin.add_view(PostView(Post))

app/admin/views.py
# coding:utf-8
from flask_admin.contrib.mongoengine import ModelView
from wtforms import fields, widgets
from flask_admin import AdminIndexView, expose, helpers
from flask_login import current_user, login_user, logout_user
from flask import redirect, url_for, request
from forms import LoginForm


class MyIndexView(AdminIndexView):
    @expose('/')
    def index(self):
        if not current_user.is_authenticated:
            return redirect(url_for('.login'))
        return super(MyIndexView, self).index()

    @expose('/login', methods=('GET', 'POST'))
    def login(self):
        form = LoginForm(request.form)
        if request.method == 'POST' and form.validate():
            user = form.get_user()
            login_user(user)
            redirect(url_for('.index'))

        self._template_args['form'] = form

        return super(MyIndexView, self).index()

    @expose('/logout/')
    def logout_view(self):
        logout_user()
        return redirect(url_for('.index'))


# Define wtforms widget and field
class CKTextAreaWidget(widgets.TextArea):
    def __call__(self, field, **kwargs):
        kwargs.setdefault('class_', 'ckeditor')
        return super(CKTextAreaWidget, self).__call__(field, **kwargs)


class CKTextAreaField(fields.TextAreaField):
    widget = CKTextAreaWidget()


class UserView(ModelView):
    can_create = False
    can_delete = False
    column_display_pk = True
    column_filters = ('name', 'email')

    edit_template = 'admin/edit_user.html'
    form_overrides = dict(description=CKTextAreaField)

    form_columns = ('name', 'email', 'description')

    def is_accessible(self):
        return current_user.is_authenticated


class PostView(ModelView):

    column_display_pk = True

    form_overrides = dict(content=CKTextAreaField)
    create_template = 'admin/create_post.html'
    edit_template = 'admin/edit_post.html'

    column_list = ('id', 'title', 'content', 'author', 'tags', 'status', 'create_time', 'modify_time')
    # column_labels = dict(id='ID',
    #                      title=u'标题',
    #                      content=u'内容',
    #                      author=u'作者',
    #                      tags=u'标签',
    #                      status=u'状态',
    #                      create_time=u'创建时间',
    #                      modify_time=u'修改时间')

    column_choices = {
        'status': [
            (0, 'draft'),
            (1, 'published')
        ]
    }

    column_filters = ('title',)

    column_searchable_list = ('content',)

    column_sortable_list = ('create_time', 'modify_time')

    def is_accessible(self):
        return current_user.is_authenticated

app/views.py
from flask import Blueprint, render_template, redirect, url_for
from models import User, Post
from flask_login import current_user, logout_user

bp = Blueprint('blog', __name__)


@bp.route('/')
@bp.route('/<int:page>')
def index(page=1):
    paginator = Post.objects.paginate(page=page, per_page=5)
    return render_template("index.html", paginator=paginator, user=current_user)


@bp.route('/posts/<string:post_id>')
def get_post(post_id):
    post = Post.objects(id=post_id).first()
    return render_template("post.html", post=post, user=current_user)


@bp.route('/about')
def about():
    user = User.objects.first()
    return render_template("about.html", user=user)


@bp.route('/contact')
def contact():
    return render_template("contact.html")


@bp.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('.index'))

app/templates/about.html
{% extends 'base.html' %}
{% block content %}
    <div class="page-heading">
        <h1>About Me</h1>
        <hr class="small">
    </div>
     {% autoescape false %}
            {{ user.description }}
     {% endautoescape %}

{% endblock %}

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    {% if post %}
        <title>{{ post.title }}</title>
        <meta name="description" content="{{ post.title }}">
        <meta name="keywords" content="{{ post.tags | format_meta_keywords }}">
        <meta name="author" content="{{ post.author.name }}">
    {% else %}
        <title>Clean Blog</title>
        <meta name="description" content="python flask react blog">
        <meta name="keywords" content="python flask react blog">
        <meta name="author" content="shin">
    {% endif %}

    <!-- Bootstrap Core CSS -->
    <link href="../static/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom CSS -->
    <!--<link href="css/clean-blog.min.css" rel="stylesheet">-->
    <link href="../static/css/clean-blog.css" rel="stylesheet">

    <!-- highlight for code -->
    <link href="../static/css/solarized_dark.css" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.1.0/css/font-awesome.min.css" rel="stylesheet" type="text/css">
    <link href='http://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='http://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800' rel='stylesheet' type='text/css'>

</head>

<body>
    <!-- Navigation -->
    <nav class="navbar navbar-default  navbar-fixed-top">
        <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <a class="navbar-brand" href="{{ url_for('blog.index') }}">CleanBlog</a>
            </div>
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li>
                        <a href="{{ url_for('blog.index') }}">Home</a>
                    </li>
                    <li>
                        <a href="{{ url_for('blog.about') }}">About</a>
                    </li>
                    <li>
                        <a href="https://github.com/defshine" rel="nofollow">Github</a>
                    </li>
                    {% if user %}
                        {% if current_user.is_authenticated %}
                            <li><a href="/admin" class="btn-info">Admin</a></li>
                            <li><a href="{{ url_for('blog.logout') }}" class="btn-info">Logout</a></li>
                        {% endif %}
                    {% endif %}
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container -->
    </nav>

    <!-- Main Content -->
    <div class="container main-container">
        <div class="row">
            <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                {% block content %}
                {% endblock %}
            </div>
        </div>
    </div>

    <hr>

    <!-- Footer -->
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2 col-md-10 col-md-offset-1">
                    <p class="copyright text-muted">Copyright &copy; CleanBlog 2015</p>
                </div>
            </div>
        </div>
    </footer>

    <!-- jQuery -->
    <script src="../static/js/lib/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="../static/js/lib/bootstrap.min.js"></script>

    <!-- Custom Theme JavaScript -->
    <script src="../static/js/clean-blog.min.js"></script>

    <script src="../static/js/lib/highlight.js"></script>
    <script>
        $(document).ready(function () {
            $('pre').each(function (i, block) {
                hljs.highlightBlock(block);
            });
        });
    </script>

</body>

</html>

app/templates/contact.html
{% extends 'base.html' %}
{% block content %}
<div>
    <h1>Contact Me</h1>
    <hr class="small">
    <span class="subheading">Have questions? I have answers (maybe).</span>
</div>
<p>Want to get in touch with me? Fill out the form below to send me a message and I will try to get back to you within
    24 hours!</p>
<!-- Contact Form - Enter your email address on line 19 of the mail/contact_me.php file to make this form work. -->
<!-- WARNING: Some web hosts do not allow emails to be sent through forms to common mail hosts like Gmail or Yahoo. It's recommended that you use a private domain email address! -->
<!-- NOTE: To use the contact form, your site must be on a live web host with PHP! The form will not work locally! -->
<form name="sentMessage" id="contactForm" novalidate>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Name</label>
            <input type="text" class="form-control" placeholder="Name" id="name" required
                   data-validation-required-message="Please enter your name.">

            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Email Address</label>
            <input type="email" class="form-control" placeholder="Email Address" id="email" required
                   data-validation-required-message="Please enter your email address.">

            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Phone Number</label>
            <input type="tel" class="form-control" placeholder="Phone Number" id="phone" required
                   data-validation-required-message="Please enter your phone number.">

            <p class="help-block text-danger"></p>
        </div>
    </div>
    <div class="row control-group">
        <div class="form-group col-xs-12 floating-label-form-group controls">
            <label>Message</label>
            <textarea rows="5" class="form-control" placeholder="Message" id="message" required
                      data-validation-required-message="Please enter a message."></textarea>

            <p class="help-block text-danger"></p>
        </div>
    </div>
    <br>

    <div id="success"></div>
    <div class="row">
        <div class="form-group col-xs-12">
            <button type="submit" class="btn btn-default">Send</button>
        </div>
    </div>
</form>
{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% block content %}
    {% if paginator.iter_pages() %}
        {% for post in paginator.items %}
            <div class="post-preview">
                <a href="/posts/{{ post.id }}">
                    <h2 class="post-title">{{ post.title }}</h2>
                </a>
                {% if post.tags %}
                    <ul class="list-unstyled list-inline">
                        {% for tag in post.tags %}
                            <li><strong><span class="label label-info">{{ tag }}</span></strong></li>
                        {% endfor %}
                    </ul>
                {% endif %}
                <p class="post-meta">Posted by <a href="{{ url_for('blog.about') }}">{{ post.author.name }}</a> on {{ post.create_time | my_format_datetime}}</p>
            </div>
            <hr>
        {% endfor %}
    {% else %}
        <h1>Welcome to CleanBlog</h1>
    {% endif %}

<!-- Pager -->
<ul class="pager">
    {% if paginator.has_prev %}
        <li class="previous">
            <a href="{{ url_for('blog.index') }}{{ paginator.pre_num }}">&larr; Newer Posts</a>
        </li>
    {% else %}
         <li class="previous disabled">
            <a href="#">&larr; Newer Posts</a>
        </li>
    {% endif %}

    {% if paginator.has_next %}
        <li class="next">
            <a href="{{ url_for('blog.index') }}{{ paginator.next_num }}">Older Posts &rarr;</a>
        </li>
    {% else %}
         <li class="next disabled">
            <a href="#">Older Posts &rarr;</a>
        </li>
    {% endif %}
</ul>
{% endblock %}

app/templates/post.html
{% extends 'base.html' %}
{% block content %}
    <div class="post-preview">
        <h1>{{ post.title }}</h1>
          {% if post.tags %}
            <ul class="list-unstyled list-inline">
                {% for tag in post.tags %}
                    <li><strong><span class="label label-info">{{ tag }}</span></strong></li>
                {% endfor %}
            </ul>
          {% endif %}
        <p class="post-meta">Posted by <a href="{{ url_for('blog.about') }}">{{ post.author.name }}</a> on {{ post.create_time | my_format_datetime}}</p>
    </div>
    <hr>
    <div>
        {% autoescape false %}
            {{ post.content }}
        {% endautoescape %}
    </div>
{% endblock %}